controllers:
    resource: ../src/Controller/
    type: attribute
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
#index:
#    path: /hello/{name}
#    controller: App\Controller\DefaultController::index
